spring.application.name=eCommerce

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
server.servlet.context-path=/ecommerce

# ===============================
# DATABASE CONFIGURATION
# ===============================
# This auto-creates DB if it doesn't exist ? very useful in dev
spring.datasource.url=jdbc:mysql://localhost:3306/myecommerce?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
